-- @Deprecated
create table xueqiu_finance
(
"code" char(6) primary key,
"reportdate" date,
"basiceps" numeric(20,2),
"epsdiluted" numeric(20,2),
"epsweighted" numeric(20,2),
"naps" numeric(20,2),
"opercashpershare" numeric(20,2),
"peropecashpershare" numeric(20,2),
"netassgrowrate" numeric(20,2),
"dilutedroe" numeric(20,2),
"weightedroe" numeric(20,2),
"mainbusincgrowrate" numeric(20,2),
"netincgrowrate" numeric(20,2),
"totassgrowrate" numeric(20,2),
"salegrossprofitrto" numeric(20,2),
"mainbusiincome" numeric(20,2),
"mainbusiprofit" numeric(20,2),
"totprofit" numeric(20,2),
"netprofit" numeric(20,2),
"totalassets" numeric(20,2),
"totalliab" numeric(20,2),
"totsharequi" numeric(20,2),
"operrevenue" numeric(20,2),
"invnetcashflow" numeric(20,2),
"finnetcflow" numeric(20,2),
"chgexchgchgs" numeric(20,2),
"cashnetr" numeric(20,2),
"cashequfinbal" numeric(20,2),
"symbol" char(8),
"name" varchar(20)
);